### ISSUE TITLE
listGitFiles 리턴값을 변경해줄수 있나요?

### ISSUE THREAD

**Issue by cloudchamb3r** [SWM-Codection/Codection-Review-Service#16]
discussion file tree 작업중에 있습니다. 
다름 아닌 파일 트리 표시에 있어서, 재귀적 형태를 띄는 PartResponse 형태로 던져주는것보다, 디렉토리를 제외한 파일목록들만 List<String> 과 같은 형태로 처리하는것이 프론트에서 사용하기 더 용이해보입니다. 
단 String 의 포맷은 최상단 레포지토리를 제외해야하고, 경로 구분자는 / 을 사용해야합니다

다음은 예시입니다 
```
[abc 레포지토리]
- 디렉토리1
   - 파일1
   - 파일2
   - 파일3
- 디렉토리2
  - 파일4
  - 파일5
  - 파일6
  - 디렉토리3
    - 파일10
- 파일7
- 파일8
- 파일9 
```
위와 같은 상황에서는 다음을 반환하면 됩니다
```
디렉토리1/파일1
디렉토리1/파일2
디렉토리1/파일3
디렉토리2/파일4
디렉토리2/파일5
디렉토리2/파일6
디렉토리2/디렉토리3/파일10
파일7
파일8
파일9
```
괜찮으시다면 반영해서 던져주시면 감사하겠습니다!

**Comment by cloudchamb3r** [comment]
자세한건 추가 검증후에 한번 요청드리겠습니다. 일단은 바로 작업 진행하지 않으셔도 됩니다

**Comment by sangcheol12** [comment]
> 자세한건 추가 검증후에 한번 더 다시 요청드리겠습니다. 일단은 바로 작업 진행하지 않으셔도 됩니다

Jgit에서 추출한 결과가 보내주신 형식과 같아 Trie 자료구조에 insert하는 부분을 제거하면 바로 가능합니다
원하시면 두가지 버전의 api를 테스트 할 수 있도록 바로 올려 드릴 수 있습다

**Comment by cloudchamb3r** [comment]
일단은 두가지 가능하도록 하면 감사합니다 
참고로 기존의 gitea에서 파일 트리를 렌더링 할때 window.config.pageData.diffFileInfo.files에 있는 자료들을 바탕으로 트리를 그린다는 것을 확인했습니다 
Addition, Deletion, IsBin, IsViewed, Name, NameHash, Type 등의 필드가 존재하는데요 
이중 Name과 IsBin 필드를 제외하면, 사실상 pr 에서만 사용되는 구조기 때문에 다른 부분은 일단은 필요 없어보입니다

<img width="931" alt="Screenshot 2024-07-28 at 5 59 28 AM" src="https://github.com/user-attachments/assets/c5eabd6b-c519-4fe9-ae41-566ee6590278">
