### ISSUE TITLE
/discussion/{repoId}/count swagger doc 미스매치

### ISSUE THREAD

**Issue by cloudchamb3r** [SWM-Codection/Codection-Review-Service#34]
최근에 변경된 `/discussion/{repoId}/count` 엔드포인트에 대해
현재 구현사항과, 스웨거의 반환값 설명의 매칭이 올바르지 않아보입니다. 
이에 대한 해결을 해주시면 감사하겠습니다

<img width="1287" alt="Screenshot 2024-08-07 at 1 09 39 PM" src="https://github.com/user-attachments/assets/10b23386-e597-4cb1-9ce9-c7a503f8a885">

**Comment by sangcheol12** [comment]
Swagger 수정 후 PR 올렸습니다
