### ISSUE TITLE
Review 서비스도 application.yml을 포함하면 어떨까요?

### ISSUE THREAD

**Issue by cloudchamb3r** [SWM-Codection/Codection-Review-Service#9]
기존의 codection-service-discovery 레포지토리와 마찬가지로, codection-review-service 역시 민감 정보들은 환경변수를 통해 받아오는 것으로 확인이 되었습니다. 
저번에 언급드린 바와 같이, 민감한 정보들이 환경 변수로 전부 관리되어, 노출이 외부로 되지 않는다면 소스 코드 상에 포함을 해도 괜찮다는 생각이 듭니다. application.yml 설정되지 않은 상태에서는 프로젝트 셋업이 힘들어지고, 베어 메탈 환경에서 프로젝트를 구성 및 실행하는데 많은 어려움을 겪게 만듭니다. 
단 여전히 공유된 환경변수에 대한 설정은 따로 팀원들끼리 비밀리 저장및 공유하는건 필요 할 것 같습니다.

**Comment by sangcheol12** [comment]
넵 각자 조심만 한다면 올려도 괜찮을 것 같습니다.
환경 변수 샘플은 어제 디코에 올려준 내용과 같습니다
